version: '3.5'

services:
  nx-cache:
    image: aaa4xu/nx-self-hosted-cache
    environment:
      MINIO_ADDRESS: http://accesskey:secretkey@host.docker.internal:9000 # "localhost" or "minio" is not valid address here!
    ports:
      - 8000:80

  minio:
    image: minio/minio:RELEASE.2020-08-08T04-50-06Z
    environment:
      MINIO_ACCESS_KEY: accesskey
      MINIO_SECRET_KEY: secretkey
    ports:
      - 9000:9000
    command: server /data
