version: '3.5'

services:
  nx-cache:
    image: nx-cache
    restart: unless-stopped
    build: .
    environment:
      MINIO_ADDRESS: http://accesskey:secretkey@host.docker.internal:9000 # localhost is not valid address here!
    ports:
      - 8000:80

  minio:
    image: minio/minio:RELEASE.2020-08-08T04-50-06Z
    environment:
      MINIO_ACCESS_KEY: accesskey
      MINIO_SECRET_KEY: secretkey
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
    command: server /data
